"""initial_schema

Revision ID: e7ea8cb49556
Revises:
Create Date: 2026-02-13 18:10:34.756145

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7ea8cb49556"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=500), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("jira_url", sa.String(length=500), nullable=True),
        sa.Column("encrypted_jira_token", sa.String(length=2000), nullable=True),
        sa.Column("jira_display_name", sa.String(length=255), nullable=True),
        sa.Column("jira_account_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_id"), ["id"], unique=False)

    op.create_table(
        "ignored_issue_type",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("issue_type", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ignored_issue_type", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ignored_issue_type_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ignored_issue_type_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "ignored_ticket",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticket_key", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ignored_ticket", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ignored_ticket_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ignored_ticket_ticket_key"), ["ticket_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ignored_ticket_user_id"), ["user_id"], unique=False)

    op.create_table(
        "session",
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_session_token"), ["token"], unique=True)

    op.create_table(
        "team_member",
        sa.Column("jira_account_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team_member", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_member_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_team_member_jira_account_id"), ["jira_account_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_member_jira_account_id"))
        batch_op.drop_index(batch_op.f("ix_team_member_id"))

    op.drop_table("team_member")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_token"))
        batch_op.drop_index(batch_op.f("ix_session_id"))

    op.drop_table("session")
    with op.batch_alter_table("ignored_ticket", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ignored_ticket_user_id"))
        batch_op.drop_index(batch_op.f("ix_ignored_ticket_ticket_key"))
        batch_op.drop_index(batch_op.f("ix_ignored_ticket_id"))

    op.drop_table("ignored_ticket")
    with op.batch_alter_table("ignored_issue_type", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ignored_issue_type_user_id"))
        batch_op.drop_index(batch_op.f("ix_ignored_issue_type_id"))

    op.drop_table("ignored_issue_type")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
