"""add_user_project_table

Revision ID: f0ae3fa7ad6c
Revises: a8c523c116da
Create Date: 2026-02-13 19:37:42.081809

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0ae3fa7ad6c"
down_revision: Union[str, Sequence[str], None] = "a8c523c116da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_project",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_key", sa.String(length=50), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("board_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "project_key", name="uq_user_project"),
    )
    with op.batch_alter_table("user_project", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_project_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_project_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_project_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_project_id"))

    op.drop_table("user_project")
    # ### end Alembic commands ###
