"""user_project_json_boards

Revision ID: f54bdc7240eb
Revises: f0ae3fa7ad6c
Create Date: 2026-02-13 19:47:16.203965

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f54bdc7240eb"
down_revision: Union[str, Sequence[str], None] = "f0ae3fa7ad6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("boards", sa.JSON(), nullable=False, server_default="[]"))
        batch_op.drop_column("board_name")
        batch_op.drop_column("board_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("board_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("board_name", sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column("boards")

    # ### end Alembic commands ###
